<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zelin Chen">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hm4_files/libs/clipboard/clipboard.min.js"></script>
<script src="hm4_files/libs/quarto-html/quarto.js"></script>
<script src="hm4_files/libs/quarto-html/popper.min.js"></script>
<script src="hm4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hm4_files/libs/quarto-html/anchor.min.js"></script>
<link href="hm4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hm4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hm4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hm4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hm4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Homework 4</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><span style="background-color: yellow;">Zelin Chen</span> </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<hr>
<div class="callout callout-style-default callout-important callout-titled" style="font-size: 0.8em;">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please read the instructions carefully before submitting your assignment.</p>
<ol type="1">
<li>This assignment requires you to only upload a <code>PDF</code> file on Canvas</li>
<li>Don’t collapse any code cells before submitting.</li>
<li>Remember to make sure all your code output is rendered properly before uploading your submission.</li>
</ol>
<p>⚠️ Please add your name to the author information in the frontmatter before submitting your assignment ⚠️</p>
</div>
</div>
<p>We will be using the following libraries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"dplyr"</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"readr"</span>, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyr"</span>, </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"purrr"</span>, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"stringr"</span>, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"corrplot"</span>, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"car"</span>, </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"caret"</span>, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"torch"</span>, </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"nnet"</span>, </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"broom"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># renv::install(packages)</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(packages, require, <span class="at">character.only=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: dplyr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: readr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tidyr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: purrr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: stringr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: corrplot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'corrplot' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: caret</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'caret' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'caret'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: torch</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'torch' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nnet</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: broom</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   dplyr    readr    tidyr    purrr  stringr corrplot      car    caret 
    TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE 
   torch     nnet    broom 
    TRUE     TRUE     TRUE </code></pre>
</div>
</div>
<p><br><br><br><br></p>
<hr>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
30 points
</div>
</div>
<div class="callout-body-container callout-body">
<p>Automatic differentiation using <code>torch</code></p>
</div>
</div>
<section id="points-1" class="level6">
<h6 class="anchored" data-anchor-id="points-1">1.1 (5 points)</h6>
<p>Consider <span class="math inline">\(g(x, y)\)</span> given by <span class="math display">\[
g(x, y) = (x - 3)^2 + (y - 4)^2.
\]</span></p>
<p>Using elementary calculus derive the expressions for</p>
<p><span class="math display">\[
\frac{d}{dx}g(x, y), \quad \text{and} \quad \frac{d}{dy}g(x, y).
\]</span> <span class="math inline">\(\frac{d}{dx}g(x, y)=2x-6\)</span> <span class="math inline">\(\frac{d}{dy}g(x, y)=2y-8\)</span></p>
<p>Using your answer from above, what is the answer to <span class="math display">\[
\frac{d}{dx}g(x, y) \Bigg|_{(x=3, y=4)} \quad \text{and} \quad \frac{d}{dy}g(x, y) \Bigg|_{(x=3, y=4)} ?
\]</span> <span class="math display">\[
\frac{d}{dx}g(x, y) \Bigg|_{(x=3, y=4)}=0\quad
\frac{d}{dy}g(x, y) \Bigg|_{(x=3, y=4)}=0
\]</span></p>
<p>Define <span class="math inline">\(g(x, y)\)</span> as a function in R, compute the gradient of <span class="math inline">\(g(x, y)\)</span> with respect to <span class="math inline">\(x=3\)</span> and <span class="math inline">\(y=4\)</span>. Does the answer match what you expected? ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Deriv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'Deriv' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">expression</span>((x <span class="sc">-</span> <span class="dv">3</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> (y <span class="sc">-</span> <span class="dv">4</span>)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>grad_g <span class="ot">&lt;-</span> <span class="fu">deriv</span>(g, <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>val_grad_g <span class="ot">&lt;-</span> <span class="fu">eval</span>(grad_g, <span class="fu">list</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="dv">4</span>))</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>val_grad_g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0
attr(,"gradient")
     x y
[1,] 0 0</code></pre>
</div>
<p>:::</p>
<hr>
</section>
<section id="points-2" class="level6">
<h6 class="anchored" data-anchor-id="points-2">1.2 (10 points)</h6>
<p><span class="math display">\[\newcommand{\u}{\boldsymbol{u}}\newcommand{\v}{\boldsymbol{v}}\]</span></p>
<p>Consider <span class="math inline">\(h(\u, \v)\)</span> given by <span class="math display">\[
h(\u, \v) = (\u \cdot \v)^3,
\]</span> where <span class="math inline">\(\u \cdot \v\)</span> denotes the dot product of two vectors, i.e., <span class="math inline">\(\u \cdot \v = \sum_{i=1}^n u_i v_i.\)</span></p>
<p>Using elementary calculus derive the expressions for the gradients</p>
<p><span class="math display">\[
\begin{aligned}
\nabla_\u h(\u, \v) &amp;= \Bigg(\frac{d}{du_1}h(\u, \v), \frac{d}{du_2}h(\u, \v), \dots, \frac{d}{du_n}h(\u, \v)\Bigg)
\end{aligned}
\]</span> <span class="math display">\[
\begin{aligned}
\nabla_\u h(\u, \v) &amp;= 3(\u \cdot \v)^2 + \v_i
\end{aligned}
\]</span></p>
<p>Using your answer from above, what is the answer to <span class="math inline">\(\nabla_\u h(\u, \v)\)</span> when <span class="math inline">\(n=10\)</span> and</p>
<p><span class="math display">\[
\begin{aligned}
\u = (-1, +1, -1, +1, -1, +1, -1, +1, -1, +1)\\
\v = (-1, -1, -1, -1, -1, +1, +1, +1, +1, +1)
\end{aligned}
\]</span> <span class="math display">\[
\begin{aligned}
\nabla_\u h(\u, \v) &amp;= [-12, -12, -12, -12, -12, 12, 12, 12, 12, 12]
\end{aligned}
\]</span></p>
<p>Define <span class="math inline">\(h(\u, \v)\)</span> as a function in R, initialize the two vectors <span class="math inline">\(\u\)</span> and <span class="math inline">\(\v\)</span> as <code>torch_tensor</code>s. Compute the gradient of <span class="math inline">\(h(\u, \v)\)</span> with respect to <span class="math inline">\(\u\)</span>. Does the answer match what you expected?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="cf">function</span>(u, v) {</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">torch_dot</span>(u, v) <span class="sc">^</span> <span class="dv">3</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">torch_tensor</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="at">requires_grad =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">torch_tensor</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">h</span>(u, v)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span><span class="fu">backward</span>()</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>u<span class="sc">$</span>grad</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>torch_tensor
-12
-12
-12
-12
-12
 12
 12
 12
 12
 12
[ CPUFloatType{10} ]</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-3" class="level6">
<h6 class="anchored" data-anchor-id="points-3">1.3 (5 points)</h6>
<p>Consider the following function <span class="math display">\[
f(z) = z^4 - 6z^2 - 3z + 4
\]</span></p>
<p>Derive the expression for <span class="math display">\[
f'(z_0) = \frac{df}{dz}\Bigg|_{z=z_0}
\]</span> and evaluate <span class="math inline">\(f'(z_0)\)</span> when <span class="math inline">\(z_0 = -3.5\)</span>.</p>
<p><span class="math display">\[
f'(z_0) = 4z_0^3-12z_0-3
\]</span> when <span class="math inline">\(z_0 = -3.5\)</span>: <span class="math display">\[
f'(z_0) = -132.5
\]</span></p>
<p>Define <span class="math inline">\(f(z)\)</span> as a function in R, and using the <code>torch</code> library compute <span class="math inline">\(f'(-3.5)\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(z) {</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  z<span class="sc">^</span><span class="dv">4</span> <span class="sc">-</span> <span class="dv">6</span> <span class="sc">*</span> z<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">3</span> <span class="sc">*</span> z <span class="sc">+</span> <span class="dv">4</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">torch_tensor</span>(<span class="sc">-</span><span class="fl">3.5</span>, <span class="at">requires_grad =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">f</span>(z)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span><span class="fu">backward</span>()</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>z<span class="sc">$</span>grad</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>torch_tensor
-132.5000
[ CPUFloatType{1} ]</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-4" class="level6">
<h6 class="anchored" data-anchor-id="points-4">1.4 (5 points)</h6>
<p>For the same function <span class="math inline">\(f\)</span>, initialize <span class="math inline">\(z[1] = -3.5\)</span>, and perform <span class="math inline">\(n=100\)</span> iterations of <strong>gradient descent</strong>, i.e.,</p>
<blockquote class="blockquote">
<p><span class="math inline">\(z[{k+1}] = z[k] - \eta f'(z[k]) \ \ \ \ \)</span> for <span class="math inline">\(k = 1, 2, \dots, 100\)</span></p>
</blockquote>
<p>Plot the curve <span class="math inline">\(f\)</span> and add taking <span class="math inline">\(\eta = 0.02\)</span>, add the points <span class="math inline">\(\{z_0, z_1, z_2, \dots z_{100}\}\)</span> obtained using gradient descent to the plot. What do you observe?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>f_prime <span class="ot">&lt;-</span> <span class="cf">function</span>(z) {</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">4</span> <span class="sc">*</span> z<span class="sc">^</span><span class="dv">3</span> <span class="sc">-</span> <span class="dv">12</span> <span class="sc">*</span> z <span class="sc">-</span> <span class="dv">3</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>eta <span class="ot">&lt;-</span> <span class="fl">0.02</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">3.5</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>z_values <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>z_values[<span class="dv">1</span>] <span class="ot">&lt;-</span> z</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> z <span class="sc">-</span> eta <span class="sc">*</span> <span class="fu">f_prime</span>(z)</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  z_values[k <span class="sc">+</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> z</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>gd_points <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> z_values, <span class="at">f_z =</span> <span class="fu">sapply</span>(z_values, f))</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>z_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(z_values)<span class="sc">-</span><span class="dv">1</span>, <span class="fu">max</span>(z_values)<span class="sc">+</span><span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>f_seq <span class="ot">&lt;-</span> <span class="fu">sapply</span>(z_seq, f)</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> z_seq, <span class="at">f_z =</span> f_seq)</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> z, <span class="at">y =</span> f_z)) <span class="sc">+</span></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">'black'</span>) <span class="sc">+</span></span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> gd_points, <span class="fu">aes</span>(<span class="at">x =</span> z, <span class="at">y =</span> f_z), <span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gradient Descent on f(z)"</span>, <span class="at">x =</span> <span class="st">"z"</span>, <span class="at">y =</span> <span class="st">"f(z)"</span>)</span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hm4_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="points-5" class="level6">
<h6 class="anchored" data-anchor-id="points-5">1.5 (5 points)</h6>
<p>Redo the same analysis as <strong>Question 1.4</strong>, but this time using <span class="math inline">\(\eta = 0.03\)</span>. What do you observe? What can you conclude from this analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>eta <span class="ot">&lt;-</span> <span class="fl">0.03</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> z <span class="sc">-</span> eta <span class="sc">*</span> <span class="fu">f_prime</span>(z)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  z_values[k <span class="sc">+</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> z</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>gd_points <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> z_values, <span class="at">f_z =</span> <span class="fu">sapply</span>(z_values, f))</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>z_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(z_values)<span class="sc">-</span><span class="dv">1</span>, <span class="fu">max</span>(z_values)<span class="sc">+</span><span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>f_seq <span class="ot">&lt;-</span> <span class="fu">sapply</span>(z_seq, f)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">z =</span> z_seq, <span class="at">f_z =</span> f_seq)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> z, <span class="at">y =</span> f_z)) <span class="sc">+</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">'black'</span>) <span class="sc">+</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> gd_points, <span class="fu">aes</span>(<span class="at">x =</span> z, <span class="at">y =</span> f_z), <span class="at">color =</span> <span class="st">'blue'</span>) <span class="sc">+</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gradient Descent on f(z)"</span>, <span class="at">x =</span> <span class="st">"z"</span>, <span class="at">y =</span> <span class="st">"f(z)"</span>)</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hm4_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The points nicely converging to a minimum, means <span class="math inline">\(\eta = 0.03\)</span> is still within an acceptable range for this function.</p>
<p><br><br><br><br> <br><br><br><br></p>
<hr>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
50 points
</div>
</div>
<div class="callout-body-container callout-body">
<p>Logistic regression and interpretation of effect sizes</p>
</div>
</div>
<p>For this question we will use the <strong>Titanic</strong> dataset from the Stanford data archive. This dataset contains information about passengers aboard the Titanic and whether or not they survived.</p>
<hr>
<section id="points-7" class="level6">
<h6 class="anchored" data-anchor-id="points-7">2.1 (5 points)</h6>
<p>Read the data from the following URL as a tibble in R. Preprocess the data such that the variables are of the right data type, e.g., binary variables are encoded as factors, and convert all column names to lower case for consistency. Let’s also rename the response variable <code>Survival</code> to <code>y</code> for convenience.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv"</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>titanic <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 887 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Sex
dbl (6): Survived, Pclass, Age, Siblings/Spouses Aboard, Parents/Children Ab...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> titanic <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(tolower) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">y =</span> survived)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(titanic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  Survived Pclass Name                        Sex     Age Siblings/Spouses Abo…¹
     &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;                       &lt;chr&gt; &lt;dbl&gt;                  &lt;dbl&gt;
1        0      3 Mr. Owen Harris Braund      male     22                      1
2        1      1 Mrs. John Bradley (Florenc… fema…    38                      1
3        1      3 Miss. Laina Heikkinen       fema…    26                      0
4        1      1 Mrs. Jacques Heath (Lily M… fema…    35                      1
5        0      3 Mr. William Henry Allen     male     35                      0
6        0      3 Mr. James Moran             male     27                      0
# ℹ abbreviated name: ¹​`Siblings/Spouses Aboard`
# ℹ 2 more variables: `Parents/Children Aboard` &lt;dbl&gt;, Fare &lt;dbl&gt;</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-8" class="level6">
<h6 class="anchored" data-anchor-id="points-8">2.2 (5 points)</h6>
<p>Visualize the correlation matrix of all numeric columns in <code>df</code> using <code>corrplot()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">corrplot</span>(<span class="at">method =</span> <span class="st">"circle"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hm4_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
<section id="points-9" class="level6">
<h6 class="anchored" data-anchor-id="points-9">2.3 (10 points)</h6>
<p>Fit a logistic regression model to predict the probability of surviving the titanic as a function of:</p>
<ul>
<li><code>pclass</code></li>
<li><code>sex</code></li>
<li><code>age</code></li>
<li><code>fare</code></li>
<li><code># siblings</code></li>
<li><code># parents</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> pclass <span class="sc">+</span> sex <span class="sc">+</span> age <span class="sc">+</span> fare <span class="sc">+</span> <span class="st">`</span><span class="at">siblings/spouses aboard</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">parents/children aboard</span><span class="st">`</span>, </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> df, </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ pclass + sex + age + fare + `siblings/spouses aboard` + 
    `parents/children aboard`, family = binomial(), data = df)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                5.297252   0.557409   9.503  &lt; 2e-16 ***
pclass                    -1.177659   0.146079  -8.062 7.52e-16 ***
sexmale                   -2.757282   0.200416 -13.758  &lt; 2e-16 ***
age                       -0.043474   0.007723  -5.629 1.81e-08 ***
fare                       0.002786   0.002389   1.166 0.243680    
`siblings/spouses aboard` -0.401831   0.110712  -3.630 0.000284 ***
`parents/children aboard` -0.106505   0.118588  -0.898 0.369127    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1182.77  on 886  degrees of freedom
Residual deviance:  780.93  on 880  degrees of freedom
AIC: 794.93

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-10" class="level6">
<h6 class="anchored" data-anchor-id="points-10">2.4 (30 points)</h6>
<p>Provide an interpretation for the slope and intercept terms estimated in <code>full_model</code> in terms of the log-odds of survival in the titanic and in terms of the odds-ratio (if the covariate is also categorical).</p>
</section>
</section>
<section id="section" class="level2 callout-hint">
<h2 class="anchored" data-anchor-id="section"></h2>
<p>Recall the definition of logistic regression from the lecture notes, and also recall how we interpreted the slope in the linear regression model (particularly when the covariate was categorical).</p>
</section>
<p>Holding other variables constant, each increase by one in the pclass is associated with a decrease in the survival by 1.177659. Being male decreases the survival by 2.757282 compared to being female. For each 1 year increase in age, decrease the survival by 0.043474. For each one-unit increase in fare increase the survival by 0.002786. For each one more sibling or spouse aboard, cause the survival decrease by 0.401831. For each one more parent or child aboard, cause the survival decrease by 0.106505.</p>
<p><br><br><br><br> <br><br><br><br></p>
<hr>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
70 points
</div>
</div>
<div class="callout-body-container callout-body">
<p>Variable selection and logistic regression in <code>torch</code></p>
</div>
</div>
<hr>
<section id="points-12" class="level6">
<h6 class="anchored" data-anchor-id="points-12">3.1 (15 points)</h6>
<p>Complete the following function <code>overview</code> which takes in two categorical vectors (<code>predicted</code> and <code>expected</code>) and outputs:</p>
<ul>
<li>The prediction accuracy</li>
<li>The prediction error</li>
<li>The false positive rate, and</li>
<li>The false negative rate</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>overview <span class="ot">&lt;-</span> <span class="cf">function</span>(predicted, expected) {</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>     total_true_positives <span class="ot">&lt;-</span> <span class="fu">sum</span>(predicted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> expected <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    total_true_negatives <span class="ot">&lt;-</span> <span class="fu">sum</span>(predicted <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> expected <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    total_false_positives <span class="ot">&lt;-</span> <span class="fu">sum</span>(predicted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> expected <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    total_false_negatives <span class="ot">&lt;-</span> <span class="fu">sum</span>(predicted <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> expected <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    accuracy <span class="ot">&lt;-</span> (total_true_positives <span class="sc">+</span> total_true_negatives) <span class="sc">/</span> <span class="fu">length</span>(expected)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    error <span class="ot">&lt;-</span> (total_false_positives <span class="sc">+</span> total_false_negatives) <span class="sc">/</span> <span class="fu">length</span>(expected)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    false_positive_rate <span class="ot">&lt;-</span> total_false_positives <span class="sc">/</span> (total_false_positives <span class="sc">+</span> total_true_negatives)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>    false_negative_rate <span class="ot">&lt;-</span> total_false_negatives <span class="sc">/</span> (total_true_positives <span class="sc">+</span> total_false_negatives)</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>        <span class="fu">data.frame</span>(</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">accuracy =</span> accuracy, </span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">error=</span>error, </span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">false_positive_rate =</span> false_positive_rate, </span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">false_negative_rate =</span> false_negative_rate</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can check if your function is doing what it’s supposed to do by evaluating</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">overview</span>(df<span class="sc">$</span>y, df<span class="sc">$</span>y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  accuracy error false_positive_rate false_negative_rate
1        1     0                   0                   0</code></pre>
</div>
</div>
<p>and making sure that the accuracy is <span class="math inline">\(100\%\)</span> while the errors are <span class="math inline">\(0\%\)</span>.</p>
<hr>
</section>
<section id="points-13" class="level6">
<h6 class="anchored" data-anchor-id="points-13">3.2 (5 points)</h6>
<p>Display an overview of the key performance metrics of <code>full_model</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>predicted_probabilities <span class="ot">&lt;-</span> <span class="fu">predict</span>(full_model, df, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>predicted_outcomes <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicted_probabilities <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>performance_metrics <span class="ot">&lt;-</span> <span class="fu">overview</span>(<span class="at">predicted =</span> predicted_outcomes, <span class="at">expected =</span> df<span class="sc">$</span>y)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>performance_metrics</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   accuracy     error false_positive_rate false_negative_rate
1 0.8015784 0.1984216            0.133945           0.3011696</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-14" class="level6">
<h6 class="anchored" data-anchor-id="points-14">3.3 (5 points)</h6>
<p>Using backward-stepwise logistic regression, find a parsimonious altenative to <code>full_model</code>, and print its <code>overview</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>step_model <span class="ot">&lt;-</span> <span class="fu">step</span>(full_model, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=794.93
y ~ pclass + sex + age + fare + `siblings/spouses aboard` + `parents/children aboard`

                            Df Deviance     AIC
- `parents/children aboard`  1   781.75  793.75
- fare                       1   782.43  794.43
&lt;none&gt;                           780.93  794.93
- `siblings/spouses aboard`  1   796.85  808.85
- age                        1   815.81  827.81
- pclass                     1   847.84  859.84
- sex                        1  1021.33 1033.33

Step:  AIC=793.75
y ~ pclass + sex + age + fare + `siblings/spouses aboard`

                            Df Deviance     AIC
- fare                       1   782.88  792.88
&lt;none&gt;                           781.75  793.75
- `siblings/spouses aboard`  1   801.59  811.59
- age                        1   816.44  826.44
- pclass                     1   852.19  862.19
- sex                        1  1025.55 1035.55

Step:  AIC=792.88
y ~ pclass + sex + age + `siblings/spouses aboard`

                            Df Deviance     AIC
&lt;none&gt;                           782.88  792.88
- `siblings/spouses aboard`  1   801.61  809.61
- age                        1   818.41  826.41
- pclass                     1   900.80  908.80
- sex                        1  1031.86 1039.86</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ pclass + sex + age + `siblings/spouses aboard`, 
    family = binomial(), data = df)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                5.532066   0.504750  10.960  &lt; 2e-16 ***
pclass                    -1.265129   0.127021  -9.960  &lt; 2e-16 ***
sexmale                   -2.736487   0.195730 -13.981  &lt; 2e-16 ***
age                       -0.043697   0.007695  -5.679 1.36e-08 ***
`siblings/spouses aboard` -0.407770   0.105197  -3.876 0.000106 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1182.77  on 886  degrees of freedom
Residual deviance:  782.88  on 882  degrees of freedom
AIC: 792.88

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>step_pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(step_model, df, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>step_predictions <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(step_pred_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">overview</span>(step_predictions, df<span class="sc">$</span>y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   accuracy     error false_positive_rate false_negative_rate
1 0.8049605 0.1950395            0.133945           0.2923977</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-15" class="level6">
<h6 class="anchored" data-anchor-id="points-15">3.4 (15 points)</h6>
<p>Using the <code>caret</code> package, setup a <strong><span class="math inline">\(5\)</span>-fold cross-validation</strong> training method using the <code>caret::trainConrol()</code> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>controls <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, using <code>control</code>, perform <span class="math inline">\(5\)</span>-fold cross validation using <code>caret::train()</code> to select the optimal <span class="math inline">\(\lambda\)</span> parameter for LASSO with logistic regression.</p>
<p>Take the search grid for <span class="math inline">\(\lambda\)</span> to be in <span class="math inline">\(\{ 2^{-20}, 2^{-19.5}, 2^{-19}, \dots, 2^{-0.5}, 2^{0} \}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>y, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>))</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>lasso_fit <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> df[, <span class="sc">!</span>(<span class="fu">names</span>(df) <span class="sc">%in%</span> <span class="st">"y"</span>)],</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> df<span class="sc">$</span>y,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"glmnet"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> controls, </span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="dv">1</span>,</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">lambda =</span> <span class="dv">2</span><span class="sc">^</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">20</span>, <span class="dv">0</span>, <span class="at">by =</span> <span class="fl">0.5</span>)</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Setting row names on a tibble is deprecated.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in storage.mode(xd) &lt;- "double": NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion

Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Setting row names on a tibble is deprecated.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in storage.mode(xd) &lt;- "double": NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion

Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Setting row names on a tibble is deprecated.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in storage.mode(xd) &lt;- "double": NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion

Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Setting row names on a tibble is deprecated.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in storage.mode(xd) &lt;- "double": NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion

Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Setting row names on a tibble is deprecated.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in storage.mode(xd) &lt;- "double": NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion

Warning in cbind2(1, newx) %*% nbeta: NAs introduced by coercion</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Setting row names on a tibble is deprecated.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in storage.mode(xd) &lt;- "double": NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>lasso_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glmnet 

887 samples
  7 predictor
  2 classes: '0', '1' 

No pre-processing
Resampling: Cross-Validated (5 fold) 
Summary of sample sizes: 709, 710, 710, 710, 709 
Resampling results across tuning parameters:

  lambda        Accuracy   Kappa    
  9.536743e-07  0.6944328  0.3184327
  1.348699e-06  0.6944328  0.3184327
  1.907349e-06  0.6944328  0.3184327
  2.697398e-06  0.6944328  0.3184327
  3.814697e-06  0.6944328  0.3184327
  5.394797e-06  0.6944328  0.3184327
  7.629395e-06  0.6944328  0.3184327
  1.078959e-05  0.6944328  0.3184327
  1.525879e-05  0.6944328  0.3184327
  2.157919e-05  0.6944328  0.3184327
  3.051758e-05  0.6944328  0.3184327
  4.315837e-05  0.6944328  0.3184327
  6.103516e-05  0.6944328  0.3184327
  8.631675e-05  0.6944328  0.3184327
  1.220703e-04  0.6944328  0.3184327
  1.726335e-04  0.6944328  0.3184327
  2.441406e-04  0.6944328  0.3184327
  3.452670e-04  0.6944328  0.3184327
  4.882812e-04  0.6944328  0.3184327
  6.905340e-04  0.6944328  0.3184327
  9.765625e-04  0.6944328  0.3184327
  1.381068e-03  0.6944328  0.3184327
  1.953125e-03  0.6944328  0.3184327
  2.762136e-03  0.6944328  0.3184327
  3.906250e-03  0.7000762  0.3274464
  5.524272e-03  0.7012061  0.3296068
  7.812500e-03  0.7011998  0.3295623
  1.104854e-02  0.7023424  0.3299795
  1.562500e-02  0.7012188  0.3262785
  2.209709e-02  0.7034724  0.3290964
  3.125000e-02  0.7011871  0.3219488
  4.419417e-02  0.6921729  0.2988830
  6.250000e-02  0.6786326  0.2680235
  8.838835e-02  0.6358408  0.1161099
  1.250000e-01  0.6144353  0.0000000
  1.767767e-01  0.6144353  0.0000000
  2.500000e-01  0.6144353  0.0000000
  3.535534e-01  0.6144353  0.0000000
  5.000000e-01  0.6144353  0.0000000
  7.071068e-01  0.6144353  0.0000000
  1.000000e+00  0.6144353  0.0000000

Tuning parameter 'alpha' was held constant at a value of 1
Accuracy was used to select the optimal model using the largest value.
The final values used for the model were alpha = 1 and lambda = 0.02209709.</code></pre>
</div>
</div>
<p>Using the information stored in <code>lasso_fit$results</code>, plot the results for cross-validation accuracy vs.&nbsp;<span class="math inline">\(log_2(\lambda)\)</span>. Choose the optimal <span class="math inline">\(\lambda^*\)</span>, and report your results for this value of <span class="math inline">\(\lambda^*\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lasso_fit<span class="sc">$</span>results, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">log2</span>(lambda), <span class="at">y =</span> Accuracy)) <span class="sc">+</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">expression</span>(log[<span class="dv">2</span>](lambda))) <span class="sc">+</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Accuracy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="hm4_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(lasso_fit<span class="sc">$</span>best)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   alpha     lambda
30     1 0.02209709</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-16" class="level6">
<h6 class="anchored" data-anchor-id="points-16">3.5 (25 points)</h6>
<p>First, use the <code>model.matrix()</code> function to convert the covariates of <code>df</code> to a matrix format</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>covariate_matrix <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(full_model)[, <span class="sc">-</span><span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, initialize the covariates <span class="math inline">\(X\)</span> and the response <span class="math inline">\(y\)</span> as <code>torch</code> tensors</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">torch_tensor</span>(<span class="fu">as.matrix</span>(covariate_matrix))</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">torch_tensor</span>(<span class="fu">as.numeric</span>(df<span class="sc">$</span>y) <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the <code>torch</code> library, initialize an <code>nn_module</code> which performs logistic regression for this dataset. (Remember that we have 6 different covariates)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>logistic <span class="ot">&lt;-</span> <span class="fu">nn_module</span>(</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">initialize =</span> <span class="cf">function</span>() {</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>    self<span class="sc">$</span>f <span class="ot">&lt;-</span> <span class="fu">nn_linear</span>(<span class="at">in_features =</span> <span class="dv">6</span>, <span class="at">out_features =</span> <span class="dv">1</span>)</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>    self<span class="sc">$</span>g <span class="ot">&lt;-</span> <span class="fu">nn_sigmoid</span>()</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>  },</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">forward =</span> <span class="cf">function</span>(x) {</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>    x <span class="sc">%&gt;%</span> self<span class="sc">$</span><span class="fu">f</span>() <span class="sc">%&gt;%</span> self<span class="sc">$</span><span class="fu">g</span>()</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">logistic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can verify that your code is right by checking that the output to the following code is a vector of probabilities:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">f</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>torch_tensor
 0.9743
 0.9973
 0.9815
 0.9959
 0.9953
 0.9842
 0.9997
 0.7720
 0.9881
 0.9121
 0.7302
 0.9999
 0.9552
 0.9990
 0.8940
 0.9998
 0.8119
 0.9710
 0.9931
 0.9664
 0.9951
 0.9945
 0.9076
 0.9854
 0.8939
 0.9989
 0.9817
 0.9622
 0.9750
 0.9712
... [the output was truncated (use n=-1 to disable)]
[ CPUFloatType{887,1} ][ grad_fn = &lt;SigmoidBackward0&gt; ]</code></pre>
</div>
</div>
<p>Now, define the loss function <code>Loss()</code> which takes in two tensors <code>X</code> and <code>y</code> and a function <code>Fun</code>, and outputs the <strong>Binary cross Entropy loss</strong> between <code>Fun(X)</code> and <code>y</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>Loss <span class="ot">&lt;-</span> <span class="cf">function</span>(X, y, Fun){</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  predicted <span class="ot">&lt;-</span> <span class="fu">Fun</span>(X)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  loss <span class="ot">&lt;-</span> <span class="fu">nnf_binary_cross_entropy</span>(predicted, y<span class="sc">$</span><span class="fu">view</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>)))</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(loss)</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Initialize an optimizer using <code>optim_adam()</code> and perform <span class="math inline">\(n=1000\)</span> steps of gradient descent in order to fit logistic regression using <code>torch</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">logistic</span>()</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>optimizer <span class="ot">&lt;-</span> <span class="fu">optim_adam</span>(f<span class="sc">$</span>parameters)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  optimizer<span class="sc">$</span><span class="fu">zero_grad</span>()</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>  loss <span class="ot">&lt;-</span> <span class="fu">Loss</span>(X, y, f)</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>  loss<span class="sc">$</span><span class="fu">backward</span>()</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>  optimizer<span class="sc">$</span><span class="fu">step</span>()</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (i <span class="sc">%%</span> <span class="dv">100</span> <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Iteration:"</span>, i, <span class="st">"Loss:"</span>, loss<span class="sc">$</span><span class="fu">item</span>(), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Iteration: 100 Loss: 4.769808 
Iteration: 200 Loss: 1.682784 
Iteration: 300 Loss: 0.7398689 
Iteration: 400 Loss: 0.6608599 
Iteration: 500 Loss: 0.61984 
Iteration: 600 Loss: 0.5913857 
Iteration: 700 Loss: 0.5717939 
Iteration: 800 Loss: 0.5580308 
Iteration: 900 Loss: 0.5479623 
Iteration: 1000 Loss: 0.5402479 </code></pre>
</div>
</div>
<p>Using the final, optimized parameters of <code>f</code>, compute the compute the predicted results on <code>X</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>predicted_probabilities <span class="ot">&lt;-</span> <span class="fu">f</span>(X) <span class="sc">%&gt;%</span> <span class="fu">as_array</span>()</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>torch_predictions <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicted_probabilities <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a><span class="fu">overview</span>(torch_predictions, df<span class="sc">$</span>y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   accuracy     error false_positive_rate false_negative_rate
1 0.7440812 0.2559188          0.07706422           0.5409357</code></pre>
</div>
</div>
<hr>
</section>
<section id="points-17" class="level6">
<h6 class="anchored" data-anchor-id="points-17">3.6 (5 points)</h6>
<p>Create a summary table of the <code>overview()</code> summary statistics for each of the <span class="math inline">\(4\)</span> models we have looked at in this assignment, and comment on their relative strengths and drawbacks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ pclass + sex + age + fare + `siblings/spouses aboard` + 
    `parents/children aboard`, family = binomial(), data = df)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                5.297252   0.557409   9.503  &lt; 2e-16 ***
pclass                    -1.177659   0.146079  -8.062 7.52e-16 ***
sexmale                   -2.757282   0.200416 -13.758  &lt; 2e-16 ***
age                       -0.043474   0.007723  -5.629 1.81e-08 ***
fare                       0.002786   0.002389   1.166 0.243680    
`siblings/spouses aboard` -0.401831   0.110712  -3.630 0.000284 ***
`parents/children aboard` -0.106505   0.118588  -0.898 0.369127    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1182.77  on 886  degrees of freedom
Residual deviance:  780.93  on 880  degrees of freedom
AIC: 794.93

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ pclass + sex + age + `siblings/spouses aboard`, 
    family = binomial(), data = df)

Coefficients:
                           Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                5.532066   0.504750  10.960  &lt; 2e-16 ***
pclass                    -1.265129   0.127021  -9.960  &lt; 2e-16 ***
sexmale                   -2.736487   0.195730 -13.981  &lt; 2e-16 ***
age                       -0.043697   0.007695  -5.679 1.36e-08 ***
`siblings/spouses aboard` -0.407770   0.105197  -3.876 0.000106 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1182.77  on 886  degrees of freedom
Residual deviance:  782.88  on 882  degrees of freedom
AIC: 792.88

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lasso_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Length Class      Mode     
a0           55    -none-     numeric  
beta        385    dgCMatrix  S4       
df           55    -none-     numeric  
dim           2    -none-     numeric  
lambda       55    -none-     numeric  
dev.ratio    55    -none-     numeric  
nulldev       1    -none-     numeric  
npasses       1    -none-     numeric  
jerr          1    -none-     numeric  
offset        1    -none-     logical  
classnames    2    -none-     character
call          5    -none-     call     
nobs          1    -none-     numeric  
lambdaOpt     1    -none-     numeric  
xNames        7    -none-     character
problemType   1    -none-     character
tuneValue     2    data.frame list     
obsLevels     2    -none-     character
param         1    -none-     list     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(torch_predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       V1        
 Min.   :0.0000  
 1st Qu.:0.0000  
 Median :0.0000  
 Mean   :0.2244  
 3rd Qu.:0.0000  
 Max.   :1.0000  </code></pre>
</div>
</div>
<div class="hidden" data-unless-format="pdf">
<div style="page-break-after: always;"></div>
</div>
<p><br><br><br><br> <br><br><br><br></p>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Session Information
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Print your <code>R</code> session information using the following command</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8 
[2] LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8
[4] LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Deriv_4.1.3    broom_1.0.5    nnet_7.3-19    torch_0.12.0   caret_6.0-94  
 [6] lattice_0.21-8 ggplot2_3.4.3  car_3.1-2      carData_3.0-5  corrplot_0.92 
[11] stringr_1.5.0  purrr_1.0.2    tidyr_1.3.1    readr_2.1.5    dplyr_1.1.4   

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0     timeDate_4032.109    farver_2.1.1        
 [4] fastmap_1.1.1        pROC_1.18.5          digest_0.6.33       
 [7] rpart_4.1.19         timechange_0.2.0     lifecycle_1.0.3     
[10] survival_3.5-5       processx_3.8.2       magrittr_2.0.3      
[13] compiler_4.3.1       rlang_1.1.1          tools_4.3.1         
[16] utf8_1.2.3           yaml_2.3.7           data.table_1.14.8   
[19] knitr_1.44           labeling_0.4.3       htmlwidgets_1.6.2   
[22] curl_5.0.2           bit_4.0.5            plyr_1.8.8          
[25] abind_1.4-5          withr_2.5.1          grid_4.3.1          
[28] stats4_4.3.1         fansi_1.0.4          e1071_1.7-14        
[31] colorspace_2.1-0     future_1.33.1        globals_0.16.2      
[34] scales_1.2.1         iterators_1.0.14     MASS_7.3-60         
[37] cli_3.6.1            crayon_1.5.2         rmarkdown_2.25      
[40] generics_0.1.3       rstudioapi_0.15.0    future.apply_1.11.1 
[43] reshape2_1.4.4       tzdb_0.4.0           proxy_0.4-27        
[46] splines_4.3.1        parallel_4.3.1       coro_1.0.3          
[49] vctrs_0.6.5          glmnet_4.1-8         hardhat_1.3.1       
[52] Matrix_1.6-5         jsonlite_1.8.7       callr_3.7.3         
[55] hms_1.1.3            bit64_4.0.5          listenv_0.9.1       
[58] foreach_1.5.2        gower_1.0.1          recipes_1.0.10      
[61] glue_1.6.2           parallelly_1.37.0    codetools_0.2-19    
[64] ps_1.7.5             shape_1.4.6          lubridate_1.9.2     
[67] stringi_1.7.12       gtable_0.3.4         munsell_0.5.0       
[70] tibble_3.2.1         pillar_1.9.0         htmltools_0.5.6     
[73] ipred_0.9-14         lava_1.7.3           R6_2.5.1            
[76] vroom_1.6.3          evaluate_0.21        backports_1.4.1     
[79] class_7.3-22         Rcpp_1.0.11          nlme_3.1-162        
[82] prodlim_2023.08.28   xfun_0.40            pkgconfig_2.0.3     
[85] ModelMetrics_1.2.2.2</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>